language: java
script: 'mvn test'
sudo: false
jdk:
  - oraclejdk8
notifications:
  irc: 'irc.esper.net#harrypotterspells'
  skip_join: true
  slack:
    rooms:
      - harrypotterspells:BIOP4jNLLLQ4H1sxnMsSzKF8#general
      - harrypotterspells:BIOP4jNLLLQ4H1sxnMsSzKF8#development
